version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - ./postgres/data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./postgres/data:/root/.pgadmin
      - ./postgres/pgadmin:/tmp/import
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    command: sh -c "/usr/local/bin/python /pgadmin/setup.py --load-servers /tmp/import/servers.json"
